Exam 1 Review

In [1]:
# Question 1

import pandas as pd

data = {
    "Student": ["Ann", "Bob", "Ann", "Bob", "Cara", "Cara"],
    "Exam": ["Midterm", "Midterm", "Final", "Final", "Midterm", "Final"],
    "Score": [85, 78, 92, 81, 88, 90]
}

df = pd.DataFrame(data)
print(df)

  Student     Exam  Score
0     Ann  Midterm     85
1     Bob  Midterm     78
2     Ann    Final     92
3     Bob    Final     81
4    Cara  Midterm     88
5    Cara    Final     90

In [ ]:
# Question 1 A
df.pivot(index='Student', columns='Exam', values='Score')

Exam     Final  Midterm
Student
Ann         92       85
Bob         81       78
Cara        90       88

In [ ]:
# Question 2 - B
df.pivot_table(index='Student', columns='Exam', values='Score', aggfunc='mean')

Exam     Final  Midterm
Student
Ann       92.0     85.0
Bob       81.0     78.0
Cara      90.0     88.0

In [2]:
#Question 3 - B
import pandas as pd
jan = pd.DataFrame({
    'CustomerID':[1,2],
    'Amount':[100,150]
})

feb = pd.DataFrame({
    'CustomerID':[1,3],
    'Amount':[120,200]
})

mar = pd.DataFrame({
    'CustomerID':[2,3],
    'Amount':[130,220]
})

pd.concat([jan, feb, mar])

   CustomerID  Amount
0           1     100
1           2     150
0           1     120
1           3     200
0           2     130
1           3     220

In [3]:
pd.merge(jan, feb, mar)

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
#Question 4 - B

import pandas as pd
import numpy as np

data = {
    "OrderID": [1, 2, 3, 4],
    "Amount": [100.0, np.nan, 200.0, np.nan]
}

df1 = pd.DataFrame(data)
print(df1)

   OrderID  Amount
0        1   100.0
1        2     NaN
2        3   200.0
3        4     NaN

In [13]:
df1.fillna(0)

   OrderID  Amount
0        1   100.0
1        2     0.0
2        3   200.0
3        4     0.0

Question 5 - C

After transforming the dataframe df, the ETL pipeline must save the result to a CSV file. Which code performs this Load step?

C.	df.to_csv('output.csv')
The rest are not pandas methods. df.write not valid for a dataframe.

Question 6 - B

Which operation is most likely part of the Transform stage of an ETL pipeline?

B. Converting JSON data into a normalized table


A. Downloading data from an API → Extraction
C. Writing a CSV file to disk → Load
D. Uploading a dataset to a database → Load

Question 7 - B

summary = sales.groupby("Region")["Amount"].sum()

Groups the data by Region. Then calculates the sum of Amount for each region

Example of aggregation, where multiple values are being combined into a single summary value per group.

A. Filtering → selecting specific rows
C. Pivoting → reshaping data structure
D. Sorting → ordering data

Question 8 - B

region = st.selectbox("Choose Region", sales["Region"].unique())
filtered = sales[sales["Region"] == region]
st.dataframe(filtered)

reamlit selectbox lets the user choose a region.
The DataFrame is then filtered based on that selection.
The result updates dynamically in app.

In [ ]:
Question 9 - B

pivot = pd.pivot_table(
    sales,
    index="Region", # rows are grouped by Region
    columns="Product", # columns are grouped by Product
    values="Amount", #data being analyzed is sales amount
    aggfunc="sum" # values are summed
)

st.dataframe(pivot)

# Output table shows the total (sum) of sales for each combination of region and product.

Question 10 - B

What does the duplicated() function return?

The duplicated() function returns a boolean Series indicating whether each row is a duplicate of a previous row. 
It marks the first occurrence of a duplicate as False and subsequent occurrences as True.

In [ ]:
Question 10 - B

What does the duplicated() function return?

The duplicated() function returns a boolean Series indicating whether each row is a duplicate of a previous row. 
It marks the first occurrence of a duplicate as False and subsequent occurrences as True.

In [15]:
data1 = [
    {
        "name": "Alice",
        "age": 30,
        "address": {
            "street": "123 Main St",
            "city": "New York"
        },
        "hobbies": ["reading", "hiking"]
    },
    {
        "name": "Bob",
        "age": 25,
        "address": {
            "street": "456 Elm St",
            "city": "Los Angeles"
        },
        "hobbies": ["gaming", "cycling"]
    }
]

In [16]:
# Q11
# How many rows and columns are in the following data frame? 
# A. 2 rows, 5 columns 

pd.json_normalize(data1)

    name  age            hobbies address.street address.city
0  Alice   30  [reading, hiking]    123 Main St     New York
1    Bob   25  [gaming, cycling]     456 Elm St  Los Angeles

In [ ]:
# Q 12 - C.	4 rows, 5 columns
# How many rows and columns are in the following data frame? 

# record_path flattens the nested list of hobbies. Tells pandas to make each hobby its own row.
# meta specifies the other fields to include in each row.
# ['address', 'street'] and ['address', 'city'] tell Pandas to extract nested fields in the address dictionary.
# errors='ignore' means avoids errors if any of the entries don’t contain one of those fields.

df = pd.json_normalize(data1, 
                       record_path='hobbies', 
                       meta=['name', 'age', ['address', 'street'], ['address', 'city']], 
                       errors='ignore')
df

         0   name age address.street address.city
0  reading  Alice  30    123 Main St     New York
1   hiking  Alice  30    123 Main St     New York
2   gaming    Bob  25     456 Elm St  Los Angeles
3  cycling    Bob  25     456 Elm St  Los Angeles

In [ ]:
# Q 13 - B.	2 rows, 1 column
# How many rows and columns are in the following data frame? 


data = next(item for item in data1 if item['name'] == 'Alice') # list comprehension to find the dictionary where name is Alice
data_df = pd.DataFrame(data['hobbies'], columns=['hobby']) # extract the hobbies list, name column hobby, and create a data frame
data_df

     hobby
0  reading
1   hiking

In [ ]:
# Q 14 - B

'''
df['Email'] selects the Email column as a pandas Series.
.str.split('@') splits each email string at '@'.
This produces a list for each row:
"ann@gmail.com" → ['ann', 'gmail.com']
"bob@yahoo.com" → ['bob', 'yahoo.com']

'''

df = pd.DataFrame({
    'Email': ['ann@gmail.com', 'bob@yahoo.com', 'cara@outlook.com']
})

df['Email'].str.split('@')

0       [ann, gmail.com]
1       [bob, yahoo.com]
2    [cara, outlook.com]
Name: Email, dtype: object

In [ ]:
# To split into separate columns, you would use
df[['username', 'domain']] = df['Email'].str.split('@', expand=True)
df

              Email username       domain
0     ann@gmail.com      ann    gmail.com
1     bob@yahoo.com      bob    yahoo.com
2  cara@outlook.com     cara  outlook.com

In [ ]:
#Q15 - A
# You run this code and click the button 4 times. What is the value of n?
#The variable n will always reset to 0 every time the app reruns.
#1


import streamlit as st
n = 0
if st.button("Click me"):
    n = n + 1
    st.write(n)

In [28]:
#Q16 - B

df = pd.DataFrame({
    'Email': ['ann@gmail.com', 'bob@yahoo.com', 'cara@outlook.com']
})

df['Domain'] = df['Email'].str.split('@').str[1]
df

# df['Email'].str.split('@') splits each email into a list like ['ann', 'gmail.com']
# .str[1] extracts the second element (index 1), which is the domain


# A .split() doesn’t work on a Series (only on strings)
# C returns lists, not just the domain
# D .domain() is not a valid pandas method

              Email       Domain
0     ann@gmail.com    gmail.com
1     bob@yahoo.com    yahoo.com
2  cara@outlook.com  outlook.com

In [ ]:
#Q17 - A
# .str.split('_'): splits the string 'sales_jan_2024.csv' into a list: ['sales', 'jan', '2024.csv'].
# .str[1]: accesses the element at index 1 of the list (the second item) for every row, which is 'jan'.

df = pd.DataFrame({
    'File': ['sales_jan_2024.csv', 'sales_feb_2024.csv']            
})

df['Month'] = df['File'].str.split('_').str[1]
df

# B: Throw an error. A pandas Series object does not have a .split() method; it requires the .str prefix.
# C: Takes the second character of the entire filename string (e.g., the 'a' in 'sales').
#D: .extract() is a pandas method, but it requires a Regular Expression (regex) with capture groups, not just a single character like '_'

                 File Month
0  sales_jan_2024.csv   jan
1  sales_feb_2024.csv   feb

Question 18 - B
What is the purpose of if __name__ == "__main__":?

Question 19 - A
To halt the debugger on a line of code we must set a:

Question 20 - B
Which panel in VS Code allows you to see all files in your workspace?

Question 21 - A
What is the term for a copy of a GitHub repository that is downloaded and stored on your local computer?

In [ ]:
# Question 22 - D

student = {
    'name': 'Alice',
    'age': 20, 
    'major': 'CS'
}

#student["major"] # bracket notation works but will throw a KeyError if the key doesn't exist. 
student.get("major") # .get() returns None instead of an error if the key is missing.

'CS'

In [ ]:
# Question 23 
numbers = [1, 2, 3, 4, 5]
squares = [x**2 for x in numbers]
print(squares)

[1, 4, 9, 16, 25]

Question 24 
Best practice - data lineage
When combining datasets, its a really good idea to retain data lineage, or a record of where the data came from. This can be done by added a column to each dataframe before concatenating.

In [ ]:
# Question 25
# when you perform arithmetic between two columns (Series), 
# the operation is vectorized. 
# This means pandas automatically matches up the values row-by-row and 
# performs the division for every employee simultaneously
# Numerator: employee_df['Tasks Completed'] targets the work output.
# Denominator: employee_df['Hours Worked'] targets the time input.
# Result: A new column named 'Productivity' is added to the DataFrame 
# containing the calculated rates

employee_df = pd.DataFrame({
    'Employee': ['Alice', 'Bob', 'Cara', 'Dan'],
    'Deparatment': ['Sales', 'Sales', 'HR', 'HR'],
    'Tasks Completed': [50, 45, 30, 25],
    'Hours Worked': [40, 35, 40, 32]
})


employee_df['Productivity'] = employee_df['Tasks Completed'] / employee_df['Hours Worked']
employee_df

  Employee Deparatment  Tasks Completed  Hours Worked  Productivity
0    Alice       Sales               50            40      1.250000
1      Bob       Sales               45            35      1.285714
2     Cara          HR               30            40      0.750000
3      Dan          HR               25            32      0.781250